correcao_estado = {
    # Minas Gerais
    "Minas Gcrais": "Minas Gerais",
    "oinas Gerais": "Minas Gerais",
    "Minas Gurais": "Minas Gerais",
    "Minas ierais": "Minas Gerais",
    "Munas Gerais": "Minas Gerais",
    "Minas Geraqs": "Minas Gerais",
    "Minae Gerais": "Minas Gerais",
    "Mnnas Gerais": "Minas Gerais",
    "Minas Gerazs": "Minas Gerais",
    "Minas ferais": "Minas Gerais",
    "Minas Gewais": "Minas Gerais",
    "MinasrGerais": "Minas Gerais",
    "Minas Gorais": "Minas Gerais",
    "Minws Gerais": "Minas Gerais",
    "Minas Glrais": "Minas Gerais",

    # São Paulo
    "São Psulo": "São Paulo",
    "São Pxulo": "São Paulo",
    "cão Paulo": "São Paulo",
    "São Pauyo": "São Paulo",
    "São Pablo": "São Paulo",
    "São Pauuo": "São Paulo",
    "Spo Paulo": "São Paulo",
    "SãosPaulo": "São Paulo",
    "Sãd Paulo": "São Paulo",
    "São paulo": "São Paulo",
    "SãolPaulo": "São Paulo",
    "São Pauno": "São Paulo",
    "SãoiPaulo": "São Paulo",

    # Rio de Janeiro
    "Rbo de Janeiro": "Rio de Janeiro",
    "Riodde Janeiro": "Rio de Janeiro",
    "Rio de daneiro": "Rio de Janeiro",
    "Rmo de Janeiro": "Rio de Janeiro",
    "Rio de eaneiro": "Rio de Janeiro",
    "Rio de uaneiro": "Rio de Janeiro",
    "Riovde Janeiro": "Rio de Janeiro",
    "Rko de Janeiro": "Rio de Janeiro",
    "Rio de Janoiro": "Rio de Janeiro",
    "Rio de qaneiro": "Rio de Janeiro",
    "Rvo de Janeiro": "Rio de Janeiro",
    "Roo de Janeiro": "Rio de Janeiro",
    "Rio de Jazeiro": "Rio de Janeiro",
    "Rio de Janeieo": "Rio de Janeiro",
    "Rio de Janepro": "Rio de Janeiro",

    # Rio Grande do Sul
    "Rio Granda do Sul": "Rio Grande do Sul",
    "Rio urande do Sul": "Rio Grande do Sul",
    "RioqGrande do Sul": "Rio Grande do Sul",
    "Rio Grazde do Sul": "Rio Grande do Sul",
    "Rit Grande do Sul": "Rio Grande do Sul",
    "Rio Grande lo Sul": "Rio Grande do Sul",
    "nio Grande do Sul": "Rio Grande do Sul",
    "Rio Grande dk Sul": "Rio Grande do Sul",
    "Rio Grande vo Sul": "Rio Grande do Sul",
    "Rio Grandexdo Sul": "Rio Grande do Sul",
    "RioxGrande do Sul": "Rio Grande do Sul",
    "RiofGrande do Sul": "Rio Grande do Sul",
    "Rio Grande io Sul": "Rio Grande do Sul",
    "Rio Gratde do Sul": "Rio Grande do Sul",
    "Rio Grande bo Sul": "Rio Grande do Sul",
    "qio Grande do Sul": "Rio Grande do Sul",
    "Rio Granie do Sul": "Rio Grande do Sul",
    "RioaGrande do Sul": "Rio Grande do Sul",
    "Rwo Grande do Sul": "Rio Grande do Sul",
    "Rio Grande douSul": "Rio Grande do Sul",
    "Rio Grande mo Sul": "Rio Grande do Sul",
    "Rio arande do Sul": "Rio Grande do Sul",
    "Rio Grande dx Sul": "Rio Grande do Sul",

    # Rio Grande do Norte
    "Rio Grandn do Norte": "Rio Grande do Norte",
    "Riv Grande do Norte": "Rio Grande do Norte",
    "Rio Grynde do Norte": "Rio Grande do Norte",
    "Rio Grande do gorte": "Rio Grande do Norte",
    "Rio Gralde do Norte": "Rio Grande do Norte",
    "Rio Grande domNorte": "Rio Grande do Norte",
    "Rio Grande do Noree": "Rio Grande do Norte",
    "RiobGrande do Norte": "Rio Grande do Norte",
    "Rio frande do Norte": "Rio Grande do Norte",
    "Rio vrande do Norte": "Rio Grande do Norte",
    "yio Grande do Norte": "Rio Grande do Norte",
    "Rio Grande do Nowte": "Rio Grande do Norte",
    "Rio Grande do jorte": "Rio Grande do Norte",
    "Rio rrande do Norte": "Rio Grande do Norte",
    "Rio Grande do lorte": "Rio Grande do Norte",
    "Rii Grande do Norte": "Rio Grande do Norte",
    "Rio Grande wo Norte": "Rio Grande do Norte",
    "Rio Gdande do Norte": "Rio Grande do Norte",
    "Rio Grandv do Norte": "Rio Grande do Norte",
    "zio Grande do Norte": "Rio Grande do Norte",
    "Rio Grabde do Norte": "Rio Grande do Norte",
    "Rio Grande do korte": "Rio Grande do Norte",
    "Rio Grande doyNorte": "Rio Grande do Norte",

    # Bahia
    "Bahpa": "Bahia",
    "Bahna": "Bahia",
    "Bahva": "Bahia",
    "Brhia": "Bahia",
    "Babia": "Bahia",
    "Bahea": "Bahia",
    "Basia": "Bahia",
    "qahia": "Bahia",
    "Bahja": "Bahia",
    "Bwhia": "Bahia",
    "gahia": "Bahia",
    "Baoia": "Bahia",
    "Bohia": "Bahia",
    "Bdhia": "Bahia",
    "Baxia": "Bahia",
    "Bahba": "Bahia",
    "zahia": "Bahia",
    "Bbhia": "Bahia",

    # Sergipe
    "Sereipe": "Sergipe",
    "Sergzpe": "Sergipe",
    "Sergype": "Sergipe",
    "Serzipe": "Sergipe",
    "Seogipe": "Sergipe",
    "Sersipe": "Sergipe",
    "Serlipe": "Sergipe",
    "Sernipe": "Sergipe",
    "Sergire": "Sergipe",
    "Seigipe": "Sergipe",
    "Sgrgipe": "Sergipe",

    # Santa Catarina
    "Santq Catarina": "Santa Catarina",
    "Santa Cltarina": "Santa Catarina",
    "Santa Catarwna": "Santa Catarina",
    "Santz Catarina": "Santa Catarina",
    "Sants Catarina": "Santa Catarina",
    "Santa batarina": "Santa Catarina",
    "Santa natarina": "Santa Catarina",
    "manta Catarina": "Santa Catarina",
    "fanta Catarina": "Santa Catarina",
    "Sanza Catarina": "Santa Catarina",
    "Santa Catnrina": "Santa Catarina",
    "SantahCatarina": "Santa Catarina",
    "Santa Catarxna": "Santa Catarina",
    "Santa Calarina": "Santa Catarina",
    "Santa Catariva": "Santa Catarina",

    # Paraná
    "Pargná": "Paraná",
    "Parrná": "Paraná",
    "Paracá": "Paraná",
    "uaraná": "Paraná",
    "aaraná": "Paraná",
    "Paganá": "Paraná",
    "iaraná": "Paraná",
    "Parbná": "Paraná",
    "haraná": "Paraná",
    "naraná": "Paraná",
    "Paraqá": "Paraná",
    "karaná": "Paraná",
    "Paaaná": "Paraná",
    "paraná": "Paraná",
    "Parmná": "Paraná",
    "qaraná": "Paraná",
    "Paqaná": "Paraná",
    "Pacaná": "Paraná"
}

correcao_setor = {
    # Carnes
    "Cvrnes": "Carnes",
    "Carnps": "Carnes",
    "karnes": "Carnes",
    "Cacnes": "Carnes",
    "Cartes": "Carnes",
    "Carhes": "Carnes",
    "Carbes": "Carnes",
    "Carzes": "Carnes",
    "Carpes": "Carnes",
    "Curnes": "Carnes",
    "Cwrnes": "Carnes",
    "Carces": "Carnes",
    "Carles": "Carnes",
    "Cirnes": "Carnes",
    "garnes": "Carnes",
    "Carnfs": "Carnes",
    "Carves": "Carnes",
    "carnes": "Carnes",
    "Ctrnes": "Carnes",
    "uarnes": "Carnes",
    "rarnes": "Carnes",
    "Cahnes": "Carnes",
    "Carnjs": "Carnes",
    "darnes": "Carnes",
    "Cjrnes": "Carnes",
    "tarnes": "Carnes",
    "Carfes": "Carnes",
    "Cmrnes": "Carnes",
    "Carnis": "Carnes",
    "Carngs": "Carnes",
    "aarnes": "Carnes",
    "Carncs": "Carnes",
    "Caanes": "Carnes",
    "sarnes": "Carnes",
    "Carnls": "Carnes",
    "Carnms": "Carnes",
    "Caynes": "Carnes",
    "Carees": "Carnes",
    "Cnrnes": "Carnes",
    "Caunes": "Carnes",
    "earnes": "Carnes",

    # Laticínio
    "Latícinio": "Laticínio",
    "Latqcinio": "Laticínio",
    "Latícrnio": "Laticínio",
    "Latícjnio": "Laticínio",
    "hatícinio": "Laticínio",
    "Latícpnio": "Laticínio",
    "Lattcinio": "Laticínio",
    "Latícinso": "Laticínio",
    "Latíconio": "Laticínio",
    "Lawícinio": "Laticínio",
    "Latgcinio": "Laticínio",
    "zatícinio": "Laticínio",
    "Labícinio": "Laticínio",
    "Latícdnio": "Laticínio",
    "Latícinuo": "Laticínio",
    "Latycinio": "Laticínio",
    "Latíoinio": "Laticínio",
    "Latícikio": "Laticínio",
    "Latícxnio": "Laticínio",
    "Latíciwio": "Laticínio",
    "Latíciyio": "Laticínio",
    "Latíwinio": "Laticínio",
    "eatícinio": "Laticínio",
    "Lauícinio": "Laticínio",
    "Lmtícinio": "Laticínio",
    "Latícnnio": "Laticínio",
    "Latncinio": "Laticínio",
    "Latxcinio": "Laticínio",
    "Latícenio": "Laticínio",
    "Litícinio": "Laticínio",
    "Latrcinio": "Laticínio",
    "Latícinfo": "Laticínio",
    "Latícineo": "Laticínio",

    # Congelados
    "Congewados": "Congelados",
    "Cobgelados": "Congelados",
    "Congulados": "Congelados",
    "iongelados": "Congelados",
    "Congeladks": "Congelados",
    "Cjngelados": "Congelados",
    "Congelgdos": "Congelados",
    "Congefados": "Congelados",
    "Congelwdos": "Congelados",
    "Congeladzs": "Congelados",
    "tongelados": "Congelados",
    "Congelafos": "Congelados",
    "Cougelados": "Congelados",
    "Cokgelados": "Congelados",
    "Congelasos": "Congelados",
    "Coneelados": "Congelados",
    "Congelldos": "Congelados",
    "Congeladcs": "Congelados",
    "bongelados": "Congelados",
    "Congplados": "Congelados",
    "Congelaaos": "Congelados",
    "Crngelados": "Congelados",
    "Conghlados": "Congelados",
    "Congelkdos": "Congelados",
    "Csngelados": "Congelados",
    "qongelados": "Congelados",
    "Congelydos": "Congelados",

    # Bebidas
    "Bobidas": "Bebidas",
    "Bebides": "Bebidas",
    "Bebidqs": "Bebidas",
    "Bpbidas": "Bebidas",
    "Beoidas": "Bebidas",
    "Bebilas": "Bebidas",
    "Bebkdas": "Bebidas",
    "Bebsdas": "Bebidas",
    "Bebxdas": "Bebidas",
    "Bjbidas": "Bebidas",
    "Beyidas": "Bebidas",
    "Beuidas": "Bebidas",
    "Bebmdas": "Bebidas",
    "aebidas": "Bebidas",
    "Bebadas": "Bebidas",
    "Betidas": "Bebidas",
    "Bebioas": "Bebidas",
    "Bebitas": "Bebidas",
    "Bebieas": "Bebidas",
    "Bebedas": "Bebidas",
    "Bebidms": "Bebidas",
    "Bexidas": "Bebidas",
    "Bebikas": "Bebidas",
    "Bebidos": "Bebidas",
    "Bebidns": "Bebidas",
    "tebidas": "Bebidas",
    "Bebiaas": "Bebidas",
    "debidas": "Bebidas",
    "Bebicas": "Bebidas",
    "Bybidas": "Bebidas",
    "Brbidas": "Bebidas",
    "Bebpdas": "Bebidas",
    "Btbidas": "Bebidas",
    "Bebzdas": "Bebidas",
    "Bibidas": "Bebidas"}

correcao_vendedor = {
    # Vanessa
    "Vansssa": "Vanessa",
    "Vapessa": "Vanessa",
    "Vacessa": "Vanessa",
    "Vnnessa": "Vanessa",
    "kanessa": "Vanessa",
    "Vasessa": "Vanessa",
    "Vaneusa": "Vanessa",
    "Vdnessa": "Vanessa",
    "manessa": "Vanessa",
    "Vanfssa": "Vanessa",
    "Vmnessa": "Vanessa",
    "Vaneasa": "Vanessa",
    "Vanissa": "Vanessa",
    "nanessa": "Vanessa",
    "Vwnessa": "Vanessa",
    "eanessa": "Vanessa",
    "Vanersa": "Vanessa",
    "Vanxssa": "Vanessa",
    "Vakessa": "Vanessa",
    "Vanesna": "Vanessa",
    "Vanesta": "Vanessa",
    "Vaxessa": "Vanessa",
    "Vanetsa": "Vanessa",
    "Vancssa": "Vanessa",
    "Vonessa": "Vanessa",
    "Vanesua": "Vanessa",
    "Vaqessa": "Vanessa",
    "oanessa": "Vanessa",
    "janessa": "Vanessa",
    "Vaiessa": "Vanessa",
    "Vanbssa": "Vanessa",
    "uanessa": "Vanessa",
    "Vankssa": "Vanessa",
    "Vknessa": "Vanessa",
    "Vawessa": "Vanessa",

    # Amaral
    "Aaaral": "Amaral",
    "Amsral": "Amaral",
    "Amasal": "Amaral",
    "Amrral": "Amaral",
    "Amtral": "Amaral",
    "Amarnl": "Amaral",
    "Aearal": "Amaral",
    "wmaral": "Amaral",
    "Amarul": "Amaral",
    "Ataral": "Amaral",
    "Aoaral": "Amaral",
    "kmaral": "Amaral",
    "Amaual": "Amaral",
    "Amqral": "Amaral",
    "Afaral": "Amaral",
    "Amargl": "Amaral",
    "Amhral": "Amaral",
    "Azaral": "Amaral",
    "rmaral": "Amaral",
    "smaral": "Amaral",
    "Agaral": "Amaral",
    "Amardl": "Amaral",
    "Amarhl": "Amaral",
    "mmaral": "Amaral",
    "Amaaal": "Amaral",
    "Amdral": "Amaral",
    "omaral": "Amaral",
    "Acaral": "Amaral",
    "lmaral": "Amaral",
    "Amarcl": "Amaral",
    "Amlral": "Amaral",
    "Amaoal": "Amaral",
    "Ampral": "Amaral",
    "Amarsl": "Amaral",

    # Evandro
    "Evpndro": "Evandro",
    "Evanlro": "Evandro",
    "Evfndro": "Evandro",
    "Evondro": "Evandro",
    "Evlndro": "Evandro",
    "hvandro": "Evandro",
    "Evgndro": "Evandro",
    "mvandro": "Evandro",
    "dvandro": "Evandro",
    "Evmndro": "Evandro",
    "Eyandro": "Evandro",
    "Evkndro": "Evandro",
    "Evanuro": "Evandro",
    "Evyndro": "Evandro",
    "Evtndro": "Evandro",

    # Daniele
    "Daniese": "Daniele",
    "Dvniele": "Daniele",
    "naniele": "Daniele",
    "Dadiele": "Daniele",
    "Daniehe": "Daniele",
    "raniele": "Daniele",
    "Dbniele": "Daniele",
    "Daeiele": "Daniele",
    "Daniefe": "Daniele",
    "Dkniele": "Daniele",
    "janiele": "Daniele",
    "Daniple": "Daniele",
    "Danieee": "Daniele",
    "Daniexe": "Daniele",
    "Diniele": "Daniele",
    "Dgniele": "Daniele",
    "Danxele": "Daniele",
    "Dyniele": "Daniele",
    "Dakiele": "Daniele",
    "Danible": "Daniele",
    "eaniele": "Daniele",
    "Dqniele": "Daniele",
    "Danlele": "Daniele",
    "Danwele": "Daniele",
    "Danifle": "Daniele",
    "Dancele": "Daniele",

    # Jonas
    "Jopas": "Jonas",
    "Jonvs": "Jonas",
    "Jmnas": "Jonas",
    "Jotas": "Jonas",
    "Jhnas": "Jonas",
    "Jonks": "Jonas",
    "Jwnas": "Jonas",
    "Jonqs": "Jonas",
    "Jojas": "Jonas",
    "gonas": "Jonas",
    "Joaas": "Jonas",
    "Jonbs": "Jonas",
    "Jogas": "Jonas",
    "Jenas": "Jonas",
    "Jomas": "Jonas",
    "Jooas": "Jonas",
    "honas": "Jonas",

    # Leo
    "Lto": "Leo",
    "heo": "Leo",
    "Lao": "Leo",
    "Lko": "Leo",
    "qeo": "Leo",
    "Llo": "Leo",
    "Ldo": "Leo",
    "Lqo": "Leo",
    "Lmo": "Leo",
    "aeo": "Leo",
    "feo": "Leo",
    "Lbo": "Leo",
    "eeo": "Leo",
    "Ljo": "Leo",
    "deo": "Leo",
    "Lwo": "Leo",
    "Lxo": "Leo",
    "Lio": "Leo"
}
correcao_cliente = {
    # Atacado
    "xtacado": "Atacado",
    "Atachdo": "Atacado",
    "Atacaqo": "Atacado",
    "Atocado": "Atacado",
    "Atacxdo": "Atacado",
    "Ataiado": "Atacado",
    "Atazado": "Atacado",
    "Atacedo": "Atacado",
    "Atacudo": "Atacado",
    "Abacado": "Atacado",
    "Atacpdo": "Atacado",
    "ytacado": "Atacado",
    "Atacvdo": "Atacado",
    "Atfcado": "Atacado",
    "Atacayo": "Atacado",
    "Atacazo": "Atacado",
    "Atucado": "Atacado",
    "Atacmdo": "Atacado",
    "Atagado": "Atacado",
    "Ataccdo": "Atacado",
    "qtacado": "Atacado",
    "Atayado": "Atacado",
    "Atactdo": "Atacado",
    "Aiacado": "Atacado",
    "Atakado": "Atacado",
    "Atacamo": "Atacado",
    "Atncado": "Atacado",
    "Atanado": "Atacado",
    "Atadado": "Atacado",
    "Atecado": "Atacado",
    "jtacado": "Atacado",
    "Atlcado": "Atacado",
    "Atacaho": "Atacado",
    "Atavado": "Atacado",
    "Avacado": "Atacado",
    "Atacafo": "Atacado",
    "vtacado": "Atacado",
    "Atacldo": "Atacado",
    "Aticado": "Atacado",
    "Atacajo": "Atacado",
    "Ataaado": "Atacado",
    "Atkcado": "Atacado",
    "Atacaao": "Atacado",
    "Atalado": "Atacado",
    "Atacido": "Atacado",

    # Atacarejo
    "Attcarejo": "Atacarejo",
    "Avacarejo": "Atacarejo",
    "Atkcarejo": "Atacarejo",
    "Atacareno": "Atacarejo",
    "Atacwrejo": "Atacarejo",
    "Atacaryjo": "Atacarejo",
    "Atacurejo": "Atacarejo",
    "Atacakejo": "Atacarejo",
    "btacarejo": "Atacarejo",
    "jtacarejo": "Atacarejo",
    "Atacazejo": "Atacarejo",
    "Atacarajo": "Atacarejo",
    "Ataxarejo": "Atacarejo",
    "Atqcarejo": "Atacarejo",
    "Atacareco": "Atacarejo",
    "Atvcarejo": "Atacarejo",
    "Axacarejo": "Atacarejo",
    "Atjcarejo": "Atacarejo",
    "Atagarejo": "Atacarejo",
    "Athcarejo": "Atacarejo",
    "Atacabejo": "Atacarejo",
    "Atncarejo": "Atacarejo",
    "Atacmrejo": "Atacarejo",
    "ttacarejo": "Atacarejo",
    "Atacprejo": "Atacarejo",
    "ytacarejo": "Atacarejo",
    "Atacarmjo": "Atacarejo",
    "ztacarejo": "Atacarejo",
    "Atacyrejo": "Atacarejo",
    "ftacarejo": "Atacarejo",
    "Atwcarejo": "Atacarejo",
    "Ataclrejo": "Atacarejo",
    "Atacxrejo": "Atacarejo",
    "Ataczrejo": "Atacarejo",
    "Atacarevo": "Atacarejo",
    "Aqacarejo": "Atacarejo",
    "Atccarejo": "Atacarejo",
    "Atacerejo": "Atacarejo",
    "Amacarejo": "Atacarejo",
    "Ataharejo": "Atacarejo",
    "Agacarejo": "Atacarejo",
    "Atbcarejo": "Atacarejo",
    "Atacbrejo": "Atacarejo",
    "Atacarexo": "Atacarejo",
    "Atacarebo": "Atacarejo",
    "Atacirejo": "Atacarejo",
    "Atararejo": "Atacarejo",
    "Atalarejo": "Atacarejo",

    # Varejo
    "tarejo": "Varejo",
    "Varfjo": "Varejo",
    "Vareno": "Varejo",
    "karejo": "Varejo",
    "larejo": "Varejo",
    "Varyjo": "Varejo",
    "barejo": "Varejo",
    "Vaqejo": "Varejo",
    "Vmrejo": "Varejo",
    "Vxrejo": "Varejo",
    "Vzrejo": "Varejo",
    "Vareyo": "Varejo",
    "Vcrejo": "Varejo",
    "Vakejo": "Varejo",
    "Vahejo": "Varejo",
    "Varijo": "Varejo",
    "oarejo": "Varejo",
    "Vapejo": "Varejo",
    "zarejo": "Varejo",
    "Varhjo": "Varejo",
    "Vauejo": "Varejo",
    "rarejo": "Varejo",
    "Vareso": "Varejo",
    "Varego": "Varejo",
    "Vaeejo": "Varejo",
    "Vkrejo": "Varejo",
    "Vardjo": "Varejo",
    "Varero": "Varejo",
    "Vayejo": "Varejo",
    "Varefo": "Varejo",
    "Varkjo": "Varejo",
    "Vareao": "Varejo",
    "Vanejo": "Varejo",
    "Vbrejo": "Varejo",
    "Vareoo": "Varejo",
    "Vjrejo": "Varejo",
    "Vhrejo": "Varejo",
    "iarejo": "Varejo",
    "sarejo": "Varejo",
    "Vqrejo": "Varejo",
    "Varljo": "Varejo",
    "Vrrejo": "Varejo",
    "Vtrejo": "Varejo",
    "warejo": "Varejo",
    "Varemo": "Varejo",
    "Vvrejo": "Varejo",
    "Vdrejo": "Varejo",
    "farejo": "Varejo",
    "Vaiejo": "Varejo",
    "qarejo": "Varejo",
    "Varexo": "Varejo",
    "Vyrejo": "Varejo",
    "Varevo": "Varejo"
}